baseURL = 'https://resbg.org/'
languageCode = 'bg-bg'
title = 'Ingress Resistance Bulgaria'
theme = 'tailbliss'
[params]
    Moto = 'Обединени в съпротива. По-силни заедно.'
    Description = 'Ingress Prime (или просто Ingress) е игра в добавена реалност за мобилни устройства, в която две организации се борят за контрол над портали, излъчващи екзотична материя. Ние сме Съпротивата и се борим да защитим свободата на човечеството от манипулация от непозната сила. Присъедини се към нас и ни помогни да победим!'
    Disable_theme_toggle = true
    Disable_blog = true
    Disable_stay_uptodate = true
    Social_media.Discord.Enabled = true
    Social_media.Discord.URl = "https://discord.gg/ncHP46Uc52"
    Social_media.Web.Enabled = true
    Social_media.Web.URl = "https://ingress.com/en"

    [menu]
        [[menu.main]]
            name = "Уроци"
            url = "/lessons/"
            weight = 1
            
        [[menu.main]]
            name = "Контакти"
            url = "/contact/"
            weight = 2

        [[menu.footer]]
            name = "Уроци"
            url = "/lessons/"
            weight = 1
            
        [[menu.footer]]
            name = "Контакти"
            url = "/contact/"
            weight = 2

    [params.P1]
        Heading = "Какво е Ingress?"
        Image = "/images/pages/map.png"
        Content = [
            { text = "Ingress е игра, която слива реалното и виртуалното. Места от социално или културно значение са обозначнени като портали - находища на нов вид енергия, наречена екзотична материя (XM). В играта има два отбора: тези, която мислят, че XM ще помогне на човечеството, наречени \"Просветлените\" (зелено), и ние - Съпротивата (синьо) - които вярваме, че XM е само способ за поробване." },
            { text = "Използвай телефона си, когато си близо до портали, за да ги превземеш за своя отбор. Свързвай портали, за да създадеш полета и да наложиш твоя отбор. " },
            { text = "Играй където и да си - Ingress е разпространена в цял свят и портали съществуват в почти всяко населено място в България. " }
        ]

    [params.P2]
        Heading = "Защо Съпротивата?"
        Image = "/images/pages/logo_blue.png"
        Content = [
            { text = "Съпротивата е тази, която иска да запази човечеството в контрол на собствената си съдба и да не позволи на сили от други измерения да ни поробят." },
            { text = "В глобален мащаб Съпротивата е водещата сила, но в България балансът е наклонен значително в полза на Просветлените. Това означава, че лесно можеш да се развиваш в играта, ако избереш нашия отбор, тъй като ще имаш изключително голям набор от портали, които да превземаш." },
            { text = "Отборът ни е сплотен, винаги приветства нови играчи и им помага да овладеят играта. " }
        ]

    [params.P3]
        Heading = "Звучи познато?"
        Content = [
            { text = "Ingress е игра, която споделя платформата си и основната си механика с Pokémon Go. В действителност двете игри са разработени от една и съща компания, но Ingress е създадена години преди Pokémon Go и е пионер в жанра." },
            { text = "За разлика от Pokémon Go, Ingress изисква тактика, стратегия и отборна игра. Докато единични играчи също могат да прогресират, значими постижения са възможни само със силна работа между съотборници в реалния свят." },
            { text = "Затова създадохме нашето общество, в което да помагаме на други играчи да прогресират по-лесно и да се наслаждават на играта, докато заедно координираме действията си, за да постигнем успех. " }
        ]
        Links = [
            { text = "Включете се в Discord", url = "https://discord.gg/ncHP46Uc52" }
        ]